'use strict';

module.exports = {
  up: async (queryInterface, Sequelize) => {
    
      await queryInterface.bulkInsert('Dish', [{
        name: 'Борщ',
        picture: "",
        price: 210,
        time: 20,
        category_id: 1,
      },
      {
        name: 'Овощной суп',
        picture: "",
        price: 220,
        time: 20,
        category_id: 1,
      },
      {
        name: 'Щи',
        picture: "",
        price: 220,
        time: 20,
        category_id: 1,
      },
      {
        name: 'Уха',
        picture: "",
        price: 200,
        time: 20,
        category_id: 1,
      },
      {
        name: 'Томатный суп',
        picture: "",
        price: 180,
        time: 20,
        category_id: 1,
      },
      {
        name: 'Крем суп',
        picture: "",
        price: 170,
        time: 20,
        category_id: 1,
      },
      {
        name: 'Coca-Cola 0,33 л',
        picture: "",
        price: 140,
        time: 2,
        category_id: 2,
      },
      {
        name: 'Club Mate Сola 0,33 л.',
        picture: "",
        price: 190,
        time: 2,
        category_id: 2,
      },
      {
        name: 'Red Bull 0,25 л.',
        picture: "",
        price: 160,
        time: 2,
        category_id: 2,
      },
      {
        name: 'Морс из чёрной смородины 1 л.',
        picture: "",
        price: 220,
        time: 2,
        category_id: 2,
      },
      {
        name: 'Морс из клубники и черники 1 л.',
        picture: "",
        price: 220,
        time: 2,
        category_id: 2,
      },
      {
        name: 'Морс из клюквы 1 л.',
        picture: "",
        price: 220,
        time: 2,
        category_id: 2,
      },
      {
        name: 'Салат Овощной',
        picture: "",
        price: 320,
        time: 10,
        category_id: 3,
      },
      {
        name: 'Салат Оливье',
        picture: "",
        price: 280,
        time: 10,
        category_id: 3,
      },
      {
        name: 'Салат с ростбифом и вешенками',
        picture: "",
        price: 400,
        time: 10,
        category_id: 3,
      },
      {
        name: 'Цезарь с куриной грудкой',
        picture: "",
        price: 380,
        time: 10,
        category_id: 3,
      },
      {
        name: 'Салат с цыплёнком и запеченным картофелем',
        picture: "",
        price: 380,
        time: 10,
        category_id: 3,
      },
      {
        name: 'Салат чука с ореховым соусом',
        picture: "",
        price: 410,
        time: 10,
        category_id: 3,
      },
      {
        name: 'Спагетти карбонара',
        picture: "",
        price: 420,
        time: 20,
        category_id: 4,
      },
      {
        name: 'Куриная грудка с пюре',
        picture: "",
        price: 400,
        time: 20,
        category_id: 4,
      },
      {
        name: 'Плов с бараниной',
        picture: "",
        price: 370,
        time: 20,
        category_id: 4,
      },
      {
        name: 'Лазанья аль форно',
        picture: "",
        price: 520,
        time: 20,
        category_id: 4,
      },
      {
        name: 'Бифштекс из баранины',
        picture: "",
        price: 560,
        time: 20,
        category_id: 4,
      },
      {
        name: 'Рис с цыплёнком в соусе унаги',
        picture: "",
        price: 410,
        time: 20,
        category_id: 4,
      },
      {
        name: 'Пицца четыре сыра',
        picture: "",
        price: 560,
        time: 20,
        category_id: 5,
      },
      {
        name: 'Пицца с ветчиной и грибами',
        picture: "",
        price: 580,
        time: 20,
        category_id: 5,
      },
      {
        name: 'Пицца Маргарита',
        picture: "",
        price: 420,
        time: 20,
        category_id: 5,
      },
      {
        name: 'Пицца с грибами',
        picture: "",
        price: 480,
        time: 20,
        category_id: 5,
      },
      {
        name: 'Пицца с вешенками, беконом и куриным филе',
        picture: "",
        price: 520,
        time: 20,
        category_id: 5,
      },
      {
        name: 'Пицца с грушей и горгонзолой',
        picture: "",
        price: 580,
        time: 20,
        category_id: 5,
      },
      {
        name: 'Тирамису',
        picture: "",
        price: 260,
        time: 5,
        category_id: 6,
      },
      {
        name: 'Торт Чизкейк',
        picture: "",
        price: 1500,
        time: 5,
        category_id: 6,
      },
      {
        name: 'Торт Медовый кейк',
        picture: "",
        price: 1500,
        time: 5,
        category_id: 6,
      },
      {
        name: 'Малиновый сорбет',
        picture: "",
        price: 490,
        time: 5,
        category_id: 6,
      },
      {
        name: 'Джелато йогурт страчателла',
        picture: "",
        price: 550,
        time: 5,
        category_id: 6,
      },
      {
        name: 'Донатс Yami',
        picture: "",
        price: 100,
        time: 5,
        category_id: 6,
      },
    ], {});

  },

  down: async (queryInterface, Sequelize) => {
      await queryInterface.bulkDelete('Dish', null, {});
  }
};
