'use strict';

module.exports = {
  up: async (queryInterface, Sequelize) => {
    
      await queryInterface.bulkInsert('Dish', [{
        name: 'Борщ',
        picture: "/img/soups/борщ.jpg",
        price: 210,
        time: 20,
        category_id: 1,
      },
      {
        name: 'Овощной суп',
        picture: "/img/soups/овощной_суп.jpg",
        price: 220,
        time: 20,
        category_id: 1,
      },
      {
        name: 'Щи',
        picture: "/img/soups/щи.jpg",
        price: 220,
        time: 20,
        category_id: 1,
      },
      {
        name: 'Уха',
        picture: "/img/soups/финская_уха.jpg",
        price: 200,
        time: 20,
        category_id: 1,
      },
      {
        name: 'Томатный суп',
        picture: "/img/soups/томатный_суп.jpg",
        price: 180,
        time: 20,
        category_id: 1,
      },
      {
        name: 'Крем суп',
        picture: "/img/soups/крем_суп.jpg",
        price: 170,
        time: 20,
        category_id: 1,
      },
      {
        name: 'Coca-Cola 0,33 л',
        picture: "/img/drinks/coca_cola.jpg",
        price: 140,
        time: 2,
        category_id: 2,
      },
      {
        name: 'Club Mate Сola 0,33 л.',
        picture: "/img/drinks/mate_cola.jpg",
        price: 190,
        time: 2,
        category_id: 2,
      },
      {
        name: 'Red Bull 0,25 л.',
        picture: "/img/drinks/red_bull.jpg",
        price: 160,
        time: 2,
        category_id: 2,
      },
      {
        name: 'Морс из чёрной смородины 1 л.',
        picture: "/img/drinks/морс_смородина.jpg",
        price: 220,
        time: 2,
        category_id: 2,
      },
      {
        name: 'Морс из клубники и черники 1 л.',
        picture: "/img/drinks/морс_черника_клубника.jpg",
        price: 220,
        time: 2,
        category_id: 2,
      },
      {
        name: 'Морс из клюквы 1 л.',
        picture: "/img/drinks/морс_клюква.jpg",
        price: 220,
        time: 2,
        category_id: 2,
      },
      {
        name: 'Салат Овощной',
        picture: "/img/salats/овощной.jpg",
        price: 320,
        time: 10,
        category_id: 3,
      },
      {
        name: 'Салат Оливье',
        picture: "/img/salats/оливье.jpg",
        price: 280,
        time: 10,
        category_id: 3,
      },
      {
        name: 'Салат с ростбифом и вешенками',
        picture: "/img/salats/ростбиф.jpg",
        price: 400,
        time: 10,
        category_id: 3,
      },
      {
        name: 'Цезарь с куриной грудкой',
        picture: "/img/salats/цезарь.jpg",
        price: 380,
        time: 10,
        category_id: 3,
      },
      {
        name: 'Салат с цыплёнком и запеченным картофелем',
        picture: "/img/salats/цепленок.jpg",
        price: 380,
        time: 10,
        category_id: 3,
      },
      {
        name: 'Салат чука с ореховым соусом',
        picture: "/img/salats/чука.jpg",
        price: 410,
        time: 10,
        category_id: 3,
      },
      {
        name: 'Спагетти карбонара',
        picture: "/img/garnish/спагетти.jpg",
        price: 420,
        time: 20,
        category_id: 4,
      },
      {
        name: 'Куриная грудка с пюре',
        picture: "/img/garnish/грудка.jpg",
        price: 400,
        time: 20,
        category_id: 4,
      },
      {
        name: 'Плов с бараниной',
        picture: "/img/garnish/плов.jpg",
        price: 370,
        time: 20,
        category_id: 4,
      },
      {
        name: 'Лазанья аль форно',
        picture: "/img/garnish/лазанья.jpg",
        price: 520,
        time: 20,
        category_id: 4,
      },
      {
        name: 'Бифштекс из баранины',
        picture: "/img/garnish/бифштекс.jpg",
        price: 560,
        time: 20,
        category_id: 4,
      },
      {
        name: 'Рис с цыплёнком в соусе унаги',
        picture: "/img/garnish/унаги.jpg",
        price: 410,
        time: 20,
        category_id: 4,
      },
      {
        name: 'Пицца четыре сыра',
        picture: "/img/pizza/4сыра.jpg",
        price: 560,
        time: 20,
        category_id: 5,
      },
      {
        name: 'Пицца с ветчиной и грибами',
        picture: "/img/pizza/ветчина.jpg",
        price: 580,
        time: 20,
        category_id: 5,
      },
      {
        name: 'Пицца Маргарита',
        picture: "/img/pizza/маргарита.jpg",
        price: 420,
        time: 20,
        category_id: 5,
      },
      {
        name: 'Пицца с грибами',
        picture: "/img/pizza/грибы.jpg",
        price: 480,
        time: 20,
        category_id: 5,
      },
      {
        name: 'Пицца с вешенками, беконом и куриным филе',
        picture: "/img/pizza/вешенки.jpg",
        price: 520,
        time: 20,
        category_id: 5,
      },
      {
        name: 'Пицца с грушей и горгонзолой',
        picture: "/img/pizza/груша.jpg",
        price: 580,
        time: 20,
        category_id: 5,
      },
      {
        name: 'Тирамису',
        picture: "/img/deserts/tiramisu.jpg",
        price: 260,
        time: 5,
        category_id: 6,
      },
      {
        name: 'Торт Чизкейк',
        picture: "/img/deserts/chizcake.jpg",
        price: 1500,
        time: 5,
        category_id: 6,
      },
      {
        name: 'Торт Медовый кейк',
        picture: "/img/deserts/medovii-keik.jpg",
        price: 1500,
        time: 5,
        category_id: 6,
      },
      {
        name: 'Малиновый сорбет',
        picture: "/img/deserts/malinovii-sorbet.jpg",
        price: 490,
        time: 5,
        category_id: 6,
      },
      {
        name: 'Джелато йогурт страчателла',
        picture: "/img/deserts/jellato-strachella.jpg",
        price: 550,
        time: 5,
        category_id: 6,
      },
      {
        name: 'Донатс Yami',
        picture: '/img/deserts/donats.jpg',
        price: 100,
        time: 5,
        category_id: 6,
      },
    ], {});

  },

  down: async (queryInterface, Sequelize) => {
      await queryInterface.bulkDelete('Dish', null, {});
  }
};
