const adminOrderAT = {
  
  GET_ORDERS: 'GET_ORDERS',
  CHANGE_STATUS_ORDER: 'CHANGE_STATUS_ORDER',
  CHANGE_ORDER: 'CHANGE_ORDER',
  INIT_ERROR_ORDER: 'INIT_ERROR_ORDER',

};

export default adminOrderAT;
