const categoriesAT = {

  INIT_CATEGORIES: 'INIT_CATEGORIES',
  GET_CATEGORIES: 'GET_CATEGORIES',
  // POST_SEND_CATEGORIES: 'POST_SEND_CATEGORIES',
  // DECREMENT_CATEGORIES: 'DECREMENT_CATEGORIES',

  INIT_ERROR_CATEGORIES: 'INIT_ERROR_CATEGORIES',
};

export default categoriesAT;
